{
  "name": "Alexi Node",
  "website": "https://github.com/alexigithub",
  "description": "i'm just a dude running a node",
  "logo": "https://learn.foundry.com/mari/Content/Resources/images/reference/atlas_random1.jpg",
  "twitter": "https://twitter.com/CryptoAlexi",
}
